### ISSUE TITLE
Posts don't load unless you refresh on page

### ISSUE THREAD

**Issue by jforaker** [MichalZalecki/react-boilerplate-lite#4]
Hey cool project!

In the `not-so-lite` branch I noticed the list of Posts don't render in the html unless you refresh on the posts route. Its interesting because they are available in `__PRELOADED_STATE__`. 

Any thoughts?

**Comment by MichalZalecki** [comment]
It's only an example how to do it on the server side. In real life, when you transition to posts page, you should check in componentDidMount whether posts are there (from `__PRELOADED_STATE__ `) or you have to fetch them.
